# Generated by Django 4.2.1 on 2023-05-25 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Service_Category',
        ),
    ]
