# Generated by Django 4.2 on 2023-05-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='product_favorites',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
