# Generated by Django 4.2 on 2023-05-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_is_finished_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
