# Generated by Django 4.2 on 2023-05-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_items_count_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
