# Generated by Django 4.2 on 2023-05-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderdetails_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
