# Generated by Django 4.2 on 2023-04-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
