# Generated by Django 4.2 on 2023-04-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
