# Generated by Django 4.2 on 2023-04-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
