# Generated by Django 4.2 on 2023-05-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_deal_discount_offer_remove_product_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer',
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
